INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1001, 'songjiang', 'male', 'Human Resource', 6000);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1002, 'lujunyi', 'male', 'Market', 6500);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1003, 'wuyong', 'female', 'Sales', 6500);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1004, 'gongsunsheng', 'male', 'Market', 7000);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1005, 'guansheng', 'male', 'Sales', 7500);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1006, 'linchong', 'female', 'Accounting', 5500);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1007, 'qinming', 'female', 'Accounting', 5800);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1008, 'huyanzhuo', 'male', 'Salse', 8000);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1009, 'huarong', 'female', 'Sales', 5000);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1010, 'chaijin', 'female', 'Market', 5700);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1011, 'liying', 'male', 'Sales', 5200);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1012, 'zhutong', 'female', 'Sales', 6300);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1013, 'luzhishen', 'male', 'Market', 6700);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1014, 'wusong', 'male', 'Market', 6800);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1015, 'dongping', 'female', 'Human Resource', 5400);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1016, 'zhangqing', 'female', 'Accounting', 6000);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1017, 'yangzhi', 'male', 'Human Resource', 5400);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1018, 'xuning', 'female', 'Accounting', 5300);
INSERT INTO `person`(`id`, `name`, `sex`, `department`, `salary`) VALUES (1019, 'lijun', 'male', 'Market', 6000);
